.\"     Title: TKMELTING
.\"    Author: Nicolas Le Novère and Marine Dumousseau <n.lenovere@gmail.com>
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 05/17/2009
.\"    Manual: Melting Manual
.\"    Source: tkmelting 0.005
.\"
.TH "TKMELTING" "1" "05/17/2009" "tkmelting 0.005" "Melting Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
tkmelting \- Tk interface to MELTING
.SH "SYNOPSIS"
.HP 10
\fBtkmelting\fR
.SH "DESCRIPTION"
.PP
\fBtkmelting\fR
starts a graphical user interface to MELTING, a program to calculate for a DNA/DNA, DNA/RNA, and RNA/RNA duplex, the enthalpy, the entropy of the helix\-coil transition, and then its melting temperature\&.
.SH "SEE ALSO"
.PP
\fBmelting\fR(1)
.SH "AUTHORS"
.PP
\fBNicolas Le Novère\fR <\&lenov@ebi\&.ac\&.uk\&>
.sp -1n
.IP "" 4
Wrote tkmelting
.PP
\fBMarine Dumousseau\fR <\&(marine@ebi\&.ac\&.uk\&>
.sp -1n
.IP "" 4
Wrote tkmelting
.PP
\fBCharles Plessy\fR <\&plessy@debian\&.org\&>
.sp -1n
.IP "" 4
Wrote and this manpage in DocBook XML for the Debian distribution\&.
.SH "COPYRIGHT"
Copyright \(co 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013 Nicolas le Novère, Marine Dumousseau
.br
Copyright \(co 2007, 2009 Charles Plessy
.br
.PP
Tkmelting is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version\&.
.PP
Tkmelting is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the GNU General Public License for more details\&.
.PP
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc\&., 59 Temple Place, Suite 330, Boston, MA 02111\-1307 USA
.PP
On Debian systems, you can find a copy of the GNU General Public License version 2 in
\fI/usr/share/common\-licences/GPL\-2\fR\&. The manpage of tkmelting can be used under the same terms as tkmelting itself\&.
.sp
